# Generated by Django 5.2.8 on 2025-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
